### ISSUE TITLE
null error when opening obverse in chrome extension

### ISSUE THREAD

**Issue by bstelzergeist** [Isaak-Malers/obverse-public#26]
When opening the obverse tab in the chrome extension, the following error is displayed.

```
Error: ENOENT: no such file or directory, open 'c:\automationTesting\obverse\tests\undefined\data-model\app-map.json'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at c:\automationTesting\obverse\chrome-extension\app.js:47:19
    at Layer.handle [as handle_request] (c:\automationTesting\obverse\node_modules\express\lib\router\layer.js:95:5)
    at next (c:\automationTesting\obverse\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (c:\automationTesting\obverse\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (c:\automationTesting\obverse\node_modules\express\lib\router\layer.js:95:5)
    at c:\automationTesting\obverse\node_modules\express\lib\router\index.js:281:22
    at param (c:\automationTesting\obverse\node_modules\express\lib\router\index.js:354:14)
    at param (c:\automationTesting\obverse\node_modules\express\lib\router\index.js:365:14)
```

**Comment by Isaak-Malers** [comment]
this error is harmless, although it is annoying.  There is a branch remove_chrome_backend, which should solve this issue once it gets merged in.
